### ISSUE TITLE
Fix for installation: 'No app name specified'

### ISSUE THREAD

**Issue by fcturner** [sualko/owncloud_piwik#1]
Hello,

Great app!! Started using Piwik right away.
But when I try to install your app, it throws an error: `No app name specified`.

Since [line 3 in your info.xml](https://github.com/sualko/owncloud_piwik/blob/master/appinfo/info.xml#L3) contains
```xml
<id>piwik</id>
```
and the official ownCloud documentation [states here](https://doc.owncloud.org/server/8.1/developer_manual/app/info.html?highlight=info#id) that **the id must be the same as the folder name**, you should point out on your readme that users should rename their folder to `apps/piwik`.

But thanks anyway, great app!!

**Comment by sualko** [comment]
Thank you for pointing this out.

**Comment by fcturner** [comment]
Man, I just wanted to say that I (as a developer myself) am *really* impressed by this app. Seems easy, but definitely nails it :smile:
