### ISSUE TITLE
Use icontentsecuritypolicymanager to whitelist external piwik installation

### ISSUE THREAD

**Issue by oparoz** [sualko/owncloud_piwik#11]
I think it should now be possible from 9.0+ to whitelist external domains instead of making modifications to the virtualhost.

https://github.com/owncloud/core/blob/master/lib/public/security/icontentsecuritypolicymanager.php

**Comment by ggeorgg** [comment]
See #3

**Comment by sualko** [comment]
Pull requests are always welcome :wink:.

**Comment by oparoz** [comment]
Yeah, I thought about it, we'll see :)
