### ISSUE TITLE
get round csp

### ISSUE THREAD

**Issue by simpleuser99** [sualko/owncloud_piwik#12]
Hello.
I'm sorry, I complied instruction, but piwik track don't work.
I install plugin, and switch on it.
my piwik domain is https://mypiwik.ru
my OC(I use 8.2.3 version) domain https://oc.ru

I filed  the owncloud admin page:
SIte id - 99
Piwik url - https://oc.ru
Use internal piwik library - disable

I maked a change in /var/www/html/owncloud/.htaccess and add line 
 
> RewriteRule ^piwik(.*)$ https://oc.ru$1 [P,L] 

in <IfModule mod_rewrite.c> part.

But in firefox firebug console I view 

> Content Security Policy: Page Setup blocked resource loading in self ("script-src https://oc.ru 'unsafe-eval'").
> 	onsubmit attribute on DIV element

and

> SyntaxError: expected expression, got '<'
> 	
> <!DOCTYPE html>
> in piwik.js

Help me please

**Comment by ggeorgg** [comment]
I am not sure but I have read somewhere that there is a "bug" in firefox with CSP. Have you tried it with chrome? 
I also have this problem in firefox but in chrome there is no error message in my console.

**Comment by sualko** [comment]
This line doesn't make sense:

> RewriteRule ^piwik(.*)$ https://oc.ru$1 [P,L]

Should be

> RewriteRule ^piwik(.*)$ https://mypiwik.ru$1 [P,L]

and your piwik url should be <code>/piwik</code>.

@ggeorgg If you have issues with csp, please use a http proxy.

**Comment by ggeorgg** [comment]
I forgot to mention that this error is already there on a new owncloud setup without owncloud_piwik installed.
