### ISSUE TITLE
Query external domain via HTTP instead HTTPS

### ISSUE THREAD

**Issue by Dallo71** [sualko/owncloud_piwik#15]
Hello,
I'm not sure where configure this but in my installation the external domain is query via HTTPS.
I'd like the query is sent via HTTP because I'm not the owner of the external domain and the server as an invalid SSL certificate there is not automatically accepted by the browsers making the requests.

Thank you

**Comment by dampfklon** [comment]
i am not shure if i understood you correct, your owncloud instance is running on https and piwik on http?

if so it is not possible to fix because modern browsers wont make unsecure requests on https sites eg. Firefox https://support.mozilla.org/en-US/kb/mixed-content-blocking-firefox

**Comment by sualko** [comment]
@dampfklon is absolutely right. This makes no sense. The only thing you can do is to add a proxy to your https host.
