### ISSUE TITLE
Tracking bei Nextcloud 9.0.52 (stable)

### ISSUE THREAD

**Issue by 8l4ckSh33p** [sualko/owncloud_piwik#17]
Piwik läuft unter https://analytics.domain1.tdl/ und Nextcloud unter https://cloud.domain2.tdl/ aber es werden keine Daten gesammelt.

Bei Nextcloud wurde auch die .htaccess angepasst und unter **<IfModule mod_rewrite.c>** `RewriteRule "^piwik/(.*)$" "https://analyics.domain1.tdl/$1" [P]` eingefügt.

Woran hängt es nun?

**Comment by 8l4ckSh33p** [comment]
Nachdem bei Nextcloud im Admin die Piwik URL von `https://analytics.domain1.tdl/` auf `//analytics.domain1.tdl/` geändert wurde. geht nun alles ;)

**Comment by 8l4ckSh33p** [comment]
zu früh gefreut... habe gerade bemerkt das nur die Login-Seite getrackt wird...

**Comment by sualko** [comment]
Versuchs mal mit "/piwik/" als URL. Ansonsten sollte ein Blick in die JS Console helfen.

**Comment by sualko** [comment]
Irgendwelche Updates, oder kann man das Ticket schließen?
