### ISSUE TITLE
Piwik app and directory don't pass oc 9.0 integrity check

### ISSUE THREAD

**Issue by danielepercivaldi** [sualko/owncloud_piwik#18]
Piwik app and directory don't pass oc 9.0 integrity check cause off wrong signature.

[piwik] => Array
(
[EXCEPTION] => Array
(
[class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
[message] => Signature data not found.
)

)

**Comment by sualko** [comment]
Not wrong, missing :wink:. I will add a signature on the next release.

**Comment by sualko** [comment]
I am sorry, I did not include an owncloud signature to the newest release, because I will go with nextcloud in the future. https://apps.nextcloud.com/apps/piwik
