### ISSUE TITLE
OC9.0.4: Undefined index: defaultValue at /owncloud/core/ajax/appconfig.php#47 

### ISSUE THREAD

**Issue by plastikschnitzer** [sualko/owncloud_piwik#19]
Hello,

if I use the app in OC 9.0.4, I get the following error in the OC error log: 

`Error PHP Undefined index: defaultValue at /owncloud/core/ajax/appconfig.php#47`

This error is also reported by some other users in the comment section here: https://apps.owncloud.com/content/show.php/piwik?content=171304

Is this a serious error or can I gently ignore it?

Best regards,

Plastikschnitzer

**Comment by sualko** [comment]
I have the same bug in another app and I was unable to fix it, but while this is just a notice, it is not very urgent. I leave this issue open, maybe some day I feel to analyse this deeper :wink:.

**Comment by plastikschnitzer** [comment]
In OC9.1.3 I also see this error in the OC log – can it be ignored as well?

`Error 	PHP 	Undefined index: HTTP_HOST at /owncloud/apps/piwik/appinfo/app.php#19 `

**Comment by sualko** [comment]
I think so, but try to change line 19 from

```
if ($_SERVER['HTTP_HOST'] !== $url) {
```

to

```
if (array_key_exists('HTTP_HOST', $_SERVER) && $_SERVER['HTTP_HOST'] !== $url) {
```

**Comment by plastikschnitzer** [comment]
Thank you, its tested and working in ownCloud and nextCloud! 
Only the initial error from this ticket remains in both systems.

**Comment by gjelsas** [comment]
I had the same error message, then changed like you proposed, and now it 
works perfect and loggs better than before!

On Debian / Nextcloud 11

Thanks!

Grüße,



Am 10.01.2017 um 16:57 schrieb Klaus:
