### ISSUE TITLE
Tracking url isn't correct 

### ISSUE THREAD

**Issue by Keithsc** [sualko/owncloud_piwik#2]
I am unable to get Owncloud tracking into Piwik. I am able to see the outbound request going to my piwik install in Firefox debugger is a 404 error The exact request is.....

https://mypiwik.com/piwik.js/piwik.php?action_name=Files - ownCloud&idsite=123&rec=1&r=124964&h=22&m=26&s=53&url=ht..................

My settings are Site ID = 123   &  Piwik URL  = https://mypiwik.com/ and Use internal piwik library = enabled.   

I think the request should just be https://mypiwik.com/piwik.php?action........  but am not 100% sure can you help ?

If I disable the "Use internal piwik Library" option then I don't see any outbound requests in firefox debugger.

Thanks
Keith.

**Comment by Keithsc** [comment]
Hi, I just upgraded our OwnCloud install from 8.1.3 to 8.2.0 and the piwik plug-in is now working ! :>)

**Comment by sualko** [comment]
Thank you for reporting. It is a bit odd, that it only works with 8.2 for your, but if it works, I will not complain ;-).
