### ISSUE TITLE
can't save admin settings

### ISSUE THREAD

**Issue by pierreozoux** [sualko/owncloud_piwik#20]
Hi!

Using your app in Nextcloud 10, but unfortunately, I can't save settings in the admin.
I tried with enter, tab, changing fields, no luck.

do you have any idea?

Thanks!

Pierre

**Comment by dampfklon** [comment]
do you use a adblocker? I had problems with the admin settings and ublock/adblockplus.

**Comment by pierreozoux** [comment]
Good catch! Thanks a lot!

**Comment by moretocome** [comment]
Thank you for developing this!

May I ask what part of the app, that triggers the adblockplus/ublock blocking of the connection? I have never had problems of that sort with other apps.

**Comment by sualko** [comment]
@moretocome I have no idea.

**Comment by methuselah-0** [comment]
I had exactly same issue but disabling add-ons didn't help.
