### ISSUE TITLE
Cannot save admin settings

### ISSUE THREAD

**Issue by gjelsas** [sualko/owncloud_piwik#21]
I'm now on Nextcloud 11 and the entries I enter into the admin settings of the piwik addon win't be saved. I disabled all addons and tried three different browsers. Any Idea?

**Comment by sualko** [comment]
Can you check your javascript console and nextcloud log?

**Comment by gjelsas** [comment]
% tail -f /var/www/owncloud/data/nextcloud.log | grep piwik                                                                                                                                                       
{"reqId":"ofAdnwrlQ9j3gM5AHQeV","remoteAddr":"","app":"PHP","message":"Undefined index: HTTP_HOST at \/var\/www\/owncloud\/apps\/piwik\/appinfo\/app.php#24","level":3,"time":"2016-12-20T21:30:02+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}

My Javascrip Console in Vivaldi browser says:

JQMIGRATE: Migrate is installed, version 1.4.0
track.js?v=c841531…:8 Uncaught TypeError: Cannot read property 'getItem' of undefined
    at track.js?v=c841531…:8
    at track.js?v=c841531…:81
(anonymous) @ track.js?v=c841531…:8
(anonymous) @ track.js?v=c841531…:81
js.js?v=c841531…:2139 Deprecation warning: tipsy is deprecated. Use tooltip instead.
jQuery.fn.tipsy @ js.js?v=c841531…:2139
(anonymous) @ admin.js?v=c841531…:44
j @ jquery.js:3099
fireWith @ jquery.js:3211
ready @ jquery.js:3417
I @ jquery.js:3433
jquery.js:8630 GET https://georgelsas.de/owncloud/data/.ocdata?t=1482265768428 403 (Forbidden)
send @ jquery.js:8630
ajax @ jquery.js:8166
checkDataProtected @ setupchecks.js?v=c841531…:211
(anonymous) @ admin.js?v=c841531…:241
j @ jquery.js:3099
fireWith @ jquery.js:3211
ready @ jquery.js:3417
I @ jquery.js:3433
VM571:1 Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.success (settings-admin.js?v=c841531…:5)
    at j (jquery.js:3099)
    at Object.fireWith [as resolveWith] (jquery.js:3211)
    at x (jquery.js:8264)
    at XMLHttpRequest.<anonymous> (jquery.js:8605)
(anonymous) @ settings-admin.js?v=c841531…:5
j @ jquery.js:3099
fireWith @ jquery.js:3211
x @ jquery.js:8264
(anonymous) @ jquery.js:8605
DevTools failed to parse SourceMap: https://georgelsas.de/owncloud/index.php/settings/admin/dist/purify.min.js.map
4additional:1 Error in event handler for (unknown): TypeError: Cannot read property 'length' of undefined
    at cip.retrieveCredentialsCallback (chrome-extension://ompiailgknfdndiefoaoiligalphfdae/chromeipass.js:1206:17)
