### ISSUE TITLE
Undefined index: HTTP_HOST, no settings shown

### ISSUE THREAD

**Issue by gjelsas** [sualko/owncloud_piwik#23]
I try to set my settings in the administration panel, but I got this error:

"Undefined index: HTTP_HOST at /var/www/nextcloud/apps/piwik/appinfo/app.php#24"

Still it wont show my settings in the administration panel but "occ config:list | grep piwik" shows:

"piwik": "{\"siteId\":\"1\",\"url\":\"\/\/mytopleveldom.ain\/piwik\/\",\"validity\":86400}",

**Comment by sualko** [comment]
Which version of nextcloud do you use? Any errors in your javascript console?

**Comment by gjelsas** [comment]
I'm on Nextcloud 11.0.0 (stable)

my Vivaldi Browser says:

Uncaught TypeError: Cannot read property 'getItem' of undefined
    at track.js?v=ec9c03f…:8
    at track.js?v=ec9c03f…:81
(anonymous) @ track.js?v=ec9c03f…:8
(anonymous) @ track.js?v=ec9c03f…:81

and:

Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.success (settings-admin.js?v=ec9c03f…:5)
    at j (jquery.js:3099)
    at Object.fireWith [as resolveWith] (jquery.js:3211)
    at x (jquery.js:8264)
    at XMLHttpRequest.<anonymous> (jquery.js:8605)

But I'm no expert at all on javascript...

**Comment by sualko** [comment]
Can you try to remove the `OC.` from https://github.com/sualko/owncloud_piwik/blob/master/js/track.js#L8 and https://github.com/sualko/owncloud_piwik/blob/master/js/track.js#L23?

**Comment by gjelsas** [comment]
Wow, that worked for me!
