### ISSUE TITLE
oC 9.13 and Piwik 3.0 - no data

### ISSUE THREAD

**Issue by airathere** [sualko/owncloud_piwik#24]
I downloaded your app (V 0.1.0) and configured site id and url as described - but after hours no data will be shown in the dashboard!
Do you have some hints for me for fixing this?

**Comment by sualko** [comment]
Hint 1: Use the latest [master version](https://github.com/sualko/owncloud_piwik/archive/master.zip) from github. Please remember to rename the folder to piwik.

Hint 2: Check your javascript console.

**Comment by airathere** [comment]
Thanks a lot for your app and time!
I installed the master version, no changes = no data (folder name is already "piwik").
Can you please explain what you mean with your 2nd hint? How do i have to do that?

**Comment by sualko** [comment]
Press Ctrl+Alt+I in your browser. Which browser do you use? Do you use oc or nc? In which version?

**Comment by sualko** [comment]
> Do you use oc or nc? In which version?

Sorry, overlooked the title.

**Comment by airathere** [comment]
I'm using Firefox ESR 45.5.1 german and oC 9.13. 
If i browse to https://my_OC_server/piwik, then click on Dashboard and press Strg+Shift+i there is a console with "JS" where i can show errors and warnings, right?
The console is empty - no errors or warnings in it

**Comment by sualko** [comment]
Browse https://my_OC_server/ as usual and check for errors

**Comment by airathere** [comment]
OK, i got this:

Content Security Policy: Die Direktive 'frame-src'  sollte nicht mehr verwendet werden. Bitte verwenden Sie stattdessen die Direktive 'child-src'. <unbekannt>
JQMIGRATE: Migrate is installed, version 1.4.0 jquery-migrate.min.js:2:542
window.controllers sollte nicht mehr verwendet werden. Verwenden Sie es nicht für die Browser-Erkennung. ace.js:1716:0

**Comment by airathere** [comment]
Do you need some more informations or is this still unresolveable?
If so, i can cut further working on it.

**Comment by airathere** [comment]
please read PN

**Comment by airathere** [comment]
Solved: unmark "Use internal piwik library" in OC Admin "Piwik Tracking"
