### ISSUE TITLE
OC9.1.3 an error occured activating the app

### ISSUE THREAD

**Issue by plastikschnitzer** [sualko/owncloud_piwik#26]
When I try to activate the app in OC9.1.3., I get the error notice "an error occured activating the app" and the following error shows up in the OC log:

Exception: {"Exception":"TypeError","Message":"Argument 1 passed to OC\\App\\DependencyAnalyzer::analyze() must be of the type array, null given, called in \/owncloud\/lib\/private\/legacy\/app.php on line 1345","Code":0,"Trace":"#0 \/owncloud\/lib\/private\/legacy\/app.php(1345): OC\\App\\DependencyAnalyzer->analyze(NULL)\n#1 \/owncloud\/lib\/private\/legacy\/app.php(337): OC_App::checkAppDependencies(Object(OC\\AllConfig), Object(OC\\L10N\\L10N), NULL)\n#2 \/owncloud\/settings\/ajax\/enableapp.php(34): OC_App::enable('piwik', NULL)\n#3 \/owncloud\/lib\/private\/Route\/Route.php(154) : runtime-created function(1): require_once('\/...')\n#4 [internal function]: __lambda_func()\n#5 \/owncloud\/lib\/private\/Route\/Router.php(280): call_user_func('\\x00lambda_12616', Array)\n#6 \/owncloud\/lib\/base.php(891): OC\\Route\\Router->match('\/settings\/ajax\/...')\n#7 \/owncloud\/index.php(54): OC::handleRequest()\n#8 {main}","File":"\/owncloud\/lib\/private\/App\/DependencyAnalyzer.php","Line":53}

**Comment by sualko** [comment]
Please test the latest beta release https://github.com/sualko/owncloud_piwik/releases

**Comment by plastikschnitzer** [comment]
Its working with the beta release, thank you! 
There is a new error showing up in the OC error log now: 

Log
Error 	PHP 	Undefined index: defaultValue at /owncloud/core/ajax/appconfig.php#47

**Comment by sualko** [comment]
see #19
