### ISSUE TITLE
Content Security Policy

### ISSUE THREAD

**Issue by ggeorgg** [sualko/owncloud_piwik#3]
Hey!

I am not sure if this really is an issue but I still wanted to ask.
I have installed owncloud and activated your app to track whats going on with piwik. I am using self signed certificates on piwik and owncloud as well. I have already been tracked once in piwik so I thought, this works all fine. But today I checked the console of firefox and saw two securitie errors:

Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://oc.domain.de 'unsafe-eval'"). 

Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf http://piwik.domain.de/piwik.js blockiert ("script-src https://oc.domain.de 'unsafe-eval'").

I am not sure if you speak german. If not, let me know I you need me to translate it.

To ensure the use of https in owncloud, I edited the .htaccess file in the root directorie of owncloud. 
In piwik, I currently do not have a redirect from http to https because of a web-cronjob that is not working with https (not sure how to change this...)

Could it be possible to add the piwik domain to the trusted domains with a function like on the following site from LukasReschke?
https://statuscode.ch/2015/04/content-security-policy-and-ownCloud/

Maybe this could be useful: https://doc.owncloud.org/server/8.1/developer_manual/app/controllers.html?highlight=csp#modifying-the-content-securicy-policy

Best regards
Georg

**Comment by sualko** [comment]
I am fine with german ;-). Owncloud has currently no function to allow global csp modifications as you can read in https://github.com/owncloud/core/issues/16927. This is not only a big issue for this app, but also for my chat [jsxc](https://github.com/jsxc). As workaround you can create a proxy with [rewrite rules](https://httpd.apache.org/docs/2.4/rewrite/proxy.html).

**Comment by buggy82** [comment]
...or modify Ownclouds CSP header in /lib/private/response.php lines 247ff to include http://piwik.domain.de next to 'self' in the 'script-src' attribute.

**Comment by ggeorgg** [comment]
So am I right that this problem will be solved with OC 9.0 like mentioned here https://github.com/owncloud/core/issues/16927 ? Will you modify your code to add the needed settings to the CSP?

**Comment by sualko** [comment]
That is right. I will add the code if I have more time.
