### ISSUE TITLE
TypeError: data.url is undefined settings-admin.js:58:11

### ISSUE THREAD

**Issue by voxdemonix** [sualko/owncloud_piwik#31]
when i try to add piwik url the firefox console said

> TypeError: data.url is undefined[[En savoir plus](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Erreurs/Unexpected_type?utm_campaign=default&utm_medium=firefox-console-errors&utm_source=mozilla)]
<anonyme> https://hostname:port/nextcloud/apps/piwik/js/settings-admin.js:58:11
	n.event.dispatch https://hostname:port/nextcloud/core/vendor/jquery/dist/jquery.min.js:3:6414
	n.event.add/r.handle https://hostname:port/nextcloud/core/vendor/jquery/dist/jquery.min.js:3:3224

Adblock is disable, referer is normal
Nextcloud 11.0.2 Stable (last version)

**Comment by KTim21** [comment]
same here
Adblock disabled
Nextcloud 12.0.0
owncloud_piwik 0.3.0

**Comment by sualko** [comment]
Sorry, I can't reproduce in FF 54. Can someone add `console.log(formData);` in https://github.com/sualko/owncloud_piwik/blob/master/js/settings-admin.js#L40 and post the output of his js console?

**Comment by KTim21** [comment]
`console.log(formData)`
gives
`Array [  ]`
in FF 45

**Comment by sualko** [comment]
Even with FF 45 and a complete reinstall of this app, I can't reproduce it.

Please execute the following in your js console and post the output:

```
$('#piwikSettings');
$('#piwikSettings form');
$('#piwikSettings [name="url"]');
$('#piwikSettings [name="url"]').val();
```

To suppress this error message you can easily change [line 45](https://github.com/sualko/owncloud_piwik/blob/master/js/settings-admin.js#L45) to `if (data.url && !data.url.match(/\/$/)) {`.

**Comment by KTim21** [comment]
```
$('#piwikSettings');
> Object { length: 1, context: HTMLDocument → additional, selector: "#piwikSettings", 1 weitere… }
```
```
$('#piwikSettings form');
> Object { selector: "#piwikSettings form", length: 0, prevObject: Object, context: HTMLDocument → additional }
```
```
$('#piwikSettings [name="url"]');
> Object { selector: "#piwikSettings [name="url"]", length: 1, prevObject: Object, context: HTMLDocument → additional, 1 weitere… }
```
```
$('#piwikSettings [name="url"]').val();
> ""
```

**Comment by sualko** [comment]
Wtf? Why is there no `form`? Sorry to bother you, but can you post the `#piwikSettings` element? Easiest way would be to execute `$('#piwikSettings').html()`.

**Comment by KTim21** [comment]
solved the problem by deactivating the app https://github.com/otetard/ownpad

there is a </form> missing

**Comment by KTim21** [comment]
created a pull request adding the missing `</form>`

**Comment by sualko** [comment]
ref otetard/ownpad#31
