### ISSUE TITLE
Can't save preferences

### ISSUE THREAD

**Issue by Rudloff** [sualko/owncloud_piwik#34]
Hello,
I'm using owncloud_piwik 0.2.0 with Owncloud 9.1.5 and I don't have any way to save the preferences:
![capture d ecran 2017-05-29 a 14 30 48](https://cloud.githubusercontent.com/assets/840125/26549882/7c8bbad0-447b-11e7-852a-d736aa2d684a.png)

**Comment by sualko** [comment]
do you use any adblocker? Errors in your js console?

**Comment by Rudloff** [comment]
Oh I totally forgot that I had uBlock Origin running, sorry. It works if I disable it.
