### ISSUE TITLE
Configuration with 2 different domains

### ISSUE THREAD

**Issue by StrangeMonkey** [sualko/owncloud_piwik#35]
Hi,

Suppose that my nextcloud is on cloud@domain.en and my piwik on monitor.domain.en

How should i configure my piwik section on nextloud ?
ID is the site ID given by piwik ? 
The URL is cloud URL or Piwik URL ?

Thanks for helping

StrangeMonkey

**Comment by sualko** [comment]
Please see https://github.com/sualko/owncloud_piwik#installation

**Comment by StrangeMonkey** [comment]
Ok, i've already check this link.
It is ambiguous, to know if one enters the URL of the piwik or the URL of the site to be monitored.

Good job for this apps.

**Comment by sualko** [comment]
> It is ambiguous, to know if one enters the URL of the piwik or the URL of the site to be monitored

Other question: How should this app determine under which url your piwik installation is reachable?
