### ISSUE TITLE
piwik app needs updating for owncloud 10

### ISSUE THREAD

**Issue by lemmy04** [sualko/owncloud_piwik#36]
the piwik app needs to be updated to work with owncloud 10.

I have installed a git snapshot, works fine but triggers code integrity warnings because it is unsigned.

**Comment by sualko** [comment]
done

**Comment by kdslkdsaldsal** [comment]
@sualko Hey, as the old apps.owncloud.com where your app is [published](https://apps.owncloud.com/content/show.php/piwik?content=171304) is deprecated are there any changes that you could publish it at the new https://marketplace.owncloud.com/ as oC 10 won't get the app currently.

**Comment by sualko** [comment]
@kdslkdsaldsal I am sorry, but I feel uncared from Owncloud and therefore I stopped all my development and moved to Nextcloud.

**Comment by kdslkdsaldsal** [comment]
Sad news but its your free decision. Thanks
