### ISSUE TITLE
custom variable

### ISSUE THREAD

**Issue by dsy2j** [sualko/owncloud_piwik#7]
How do I add a custom variable in dashboard?
like this
http://i.imgur.com/P3uwZNL.jpg

and "Empty custom variable slots on index 1 and 2"
Could you tell me more about detail, which file need to modify

**Comment by sualko** [comment]
> Could you tell me more about detail, which file need to modify

No need for any modification. In piwik these slots are available by default.

>  Empty custom variable slots on index 1 and 2

This should only indicate, that those will be overwritten if you use them elsewhere.

**Comment by dsy2j** [comment]
thanks for your reply, I have added it.
