### ISSUE TITLE
2 or more owncloud

### ISSUE THREAD

**Issue by dsy2j** [sualko/owncloud_piwik#8]
If I haave 2 or more owncloud with piwik owncloud app, but I just use one piwik server.
What config need to be mondify if want to do in this condition?
I try to insert piwik code to owncloud files like this website(http://www.kiloroot.com/owncloud-piwik-apache-access-log-monitored-self-hosted-enterprise-file-sharing/#comments)
/var/www/owncloud/core/templates/layout.user.php
/var/www/owncloud/core/templates/layout.guest.php
/var/www/owncloud/apps/files_sharing/templates/public.php
But piwik don't receive any data, what's wrong with it

**Comment by sualko** [comment]
Why do you use my app and these templete modifications at the same time?

No special configuration is needed. Just create two new sites in piwik and enter the corresponding site id in oc admin settings.

**Comment by dsy2j** [comment]
Not at the same time.
If I want to use the same Piwik server, I should use the templete modifications at the second owncloud, right?
OK. I know.

**Comment by sualko** [comment]
> I should use the templete modifications at the second owncloud, right?

No.

> Just create two new sites in piwik and enter the corresponding site id in oc admin settings.
