### ISSUE TITLE
Need Installation Help

### ISSUE THREAD

**Issue by j4mb4l4j4** [sualko/owncloud_piwik#9]
Hi, I think i need a little help, because I kinda don't get the instruction.

I installed Piwik with the URL:

https://mypiwikinstallation.com

I can successfully log in the Admin Interface.
But it is saying, that my website I created didn't have a Tracking Code inserted.

My Owncloud Installation is:

https://myowncloud.com

So when I go to my Admin Interface in Owncloud an put the 

ID: 1
Piwik Installation: https://piwikinstallation.com

I still get a message in Piwik, that my Owncloud Installation has no Tracking Code.
Don't i have to put the Tracking Code somewhere inside Owncloud ?

**Comment by sualko** [comment]
You ran into the very restrictive content security policy of owncloud. It defines that requests to different domains (as your host) get denied. Until https://github.com/owncloud/core/issues/16927 is implemented, you have to define a ProxyPass or rewriterule from your owncloud vserver to your piwik vserver (e.g. https://myowncloud.com/piwik/ -> https://piwikinstallation.com).

**Comment by j4mb4l4j4** [comment]
Hi, thanks for the quick reply, I really appreciate that kind of help, cause I think I'm maybe not the only guy with that problem :-)

I still got my problems to get it working.
As you recommended me, I did a Rewrite rule in my .htacces file in my Owncloud Installation ( or do I have to set it in my Owncloud vHost Container ? ):


/var/www/html/myowncloud.com/.htaccess

    <IfModule mod_rewrite.c>
    ...
    RewriteRule ^piwik(.*)$ https://mypiwik.com$1 [R=301,L]
    ...
    </IfModule>


When I open my Piwik Webinterface I still get the message:

"No analytics data has been tracked for this website yet. Please set up the JavaScript tracking code on your website and refresh the page.
Tracking code for myowncloud.com"


Is your Applikation calling piwik over https://myowncloud.com/piwik and gets redirected to https://mypiwik.com ?

In my Owncloud Admin Area, do I have to put in the Field:
"My Piwik Installation", the Path:

https://myowncloud.com/piwik ?

or still

https://mypiwik.com ?

**Comment by sualko** [comment]
As mentioned before, you need to proxy all requests. Therefore replace 
r=301 with p.

I will extend the installation guide by some lines to make it more clear.

**Comment by j4mb4l4j4** [comment]
Hi, thanks for the installation update.
I'll test your advice the next days.

I was kinda busy cause of a linux exam.

Maybe I'll run in some issues cause of the SSL Encryption, but I'll give you a summary when I'm done.
